title: "Fariha Yasmin"
description: "Physics, computational materials science, DFT, and Quantum ESPRESSO"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache